dist: trusty
sudo: required
language: python
python:
  - "2.7.14"
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install pytest pytest-cov
  - pip install coveralls
  
script:
  - python test_palindromes.py 
  - pylint palindromes.py
  - pycodestyle --cov=.
  - coverage report
 
after_success:
coveralls